apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-test
  template:
    metadata:
      labels:
        app: jenkins-test
    spec:
      containers:
        - name: jenkins-test
          image: nikishka/jenkin-test-v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-test-service
spec:
  type: NodePort
  selector:
    app: jenkins-test
  ports:
    - port: 8083
      targetPort: 8083
